---
- hosts: all
  # gather_facts: no
  become: yes
  vars:
    pathimages: /images
    imagename: W10-7.05-PostoAtendimentoMultihardware
    pathimage: "{{pathimages}}/{{imagename}}"
    imagem:
    
        #1166e4693bb9e1edbea499aee3ca09a3  /images/W10-7.05-PostoAtendimentoMultihardware/d1.original.uuids
        #2cfd36a0e381b432a55b929f796ed3d4  /images/W10-7.05-PostoAtendimentoMultihardware/d1.original.fstypes
        #4b25621c8bd7afd28cf0b85e6c52a06c  /images/W10-7.05-PostoAtendimentoMultihardware/d1.mbr
        #fe438f0348b039c39da50e69aa39ba8d  /images/W10-7.05-PostoAtendimentoMultihardware/d1.partitions
        #d41d8cd98f00b204e9800998ecf8427e  /images/W10-7.05-PostoAtendimentoMultihardware/d1.original.swapuuids
        #e0b66858a524188d49b0a3fae494de7d  /images/W10-7.05-PostoAtendimentoMultihardware/d1.minimum.partitions
        #dbf5e5c41eccc1de3e8166f85148dcb8  /images/W10-7.05-PostoAtendimentoMultihardware/d1.fixed_size_partitions
        #3e4222b9c9905f4c9b0fb05c481c7664  /images/W10-7.05-PostoAtendimentoMultihardware/d1p1.img
        #d2177b445a0e87e6015b30e40693b931  /images/W10-7.05-PostoAtendimentoMultihardware/d1p2.img
        #f3a8495956717f9f8aa05578f3ec681f  /images/W10-7.05-PostoAtendimentoMultihardware/d1p3.img
      
      - arquivo: d1.original.uuids
        hash_src: 1166e4693bb9e1edbea499aee3ca09a3
      - arquivo: d1.original.fstypes
        hash_src: 2cfd36a0e381b432a55b929f796ed3d4
      - arquivo: d1.mbr
        hash_src: 4b25621c8bd7afd28cf0b85e6c52a06c
      - arquivo: d1.partitions
        hash_src: fe438f0348b039c39da50e69aa39ba8d
      - arquivo: d1.original.swapuuids
        hash_src: d41d8cd98f00b204e9800998ecf8427e
      - arquivo: d1.minimum.partitions
        hash_src: e0b66858a524188d49b0a3fae494de7d
      - arquivo: d1.fixed_size_partitions
        hash_src: dbf5e5c41eccc1de3e8166f85148dcb8
        #      - arquivo: d1p1.img
        #        hash_src: 3e4222b9c9905f4c9b0fb05c481c7664
        #      - arquivo: d1p2.img
        #        hash_src: d2177b445a0e87e6015b30e40693b931
        #      - arquivo: d1p3.img
        #        hash_src: f3a8495956717f9f8aa05578f3ec681f

      

  tasks:
  
          #- name: remove a pasta orig de dentro da imagem
          #file:
          #state: absent
          #path: "{{ pathimage }}/orig/"

  - name: stats dos arquivos
    stat: path={{ pathimage }}/{{ item.arquivo }} checksum_algorithm=md5
    register: r
    loop: "{{ imagem }}"
    
    #  - name: debug do retorno
    #    debug:
    #      var: item
    #    failed_when:  r.results.hash_src != r.results.item.stat.checksum
    #    loop: "{{ r  | dict2items }}"
    #    loop: "{{ r.results.item | dict2items }}"
  
  - name: "checagem de hash"
    debug:
            #      msg: "{{item.invocation.module_args.path}}: {{item.stat.exists}}"
            msg: "{{item.item.arquivo}} - {{item.stat.exists}} - {{item.stat.checksum}} != {{item.item.hash_src}}"
    when: item.stat.checksum  != item.item.hash_src
    #failed_when: item.stat.checksum  != item.item.hash_src
    with_items:
    - "{{r.results}}"
   
  #- name: debug de path so pra teste
  #  debug:  #/mnt/d/Comum/fog/images/W10-7.05-PostoAtendimentoMultihardware
  #    msg: "### /mnt/d/Comum/fog/images/{{imagename}}/{{item.item.arquivo}} ### {{pathimage}}/{{item.item.arquivo}} ###"
  #  when: item.stat.checksum  != item.item.hash_src
  #  with_items:
  #  - "{{r.results}}"


  - name: Copy file with owner and permissions
    copy:
      src: "/mnt/d/Comum/fog/images/{{imagename}}/{{item.item.arquivo}}"
      dest: "{{pathimage}}/{{item.item.arquivo}}"
      owner: fog
      group: fog
      mode: '0644'
    when: item.stat.checksum  != item.item.hash_src
    with_items:
    - "{{r.results}}"
    



