---
- hosts: all
  tasks:
  - name: obter checksum do authorized_keys
    stat:
      path: /home/samc/.ssh/authorized_keys
      checksum_algorithm: sha256
      get_checksum: yes
    register: key_stat


  - name: comparar com o checksum original
    fail:
      msg: "Arquivo incorreto"
    when: key_stat.stat.checksum != '0113446c8907ffc3eb8ae02222f99b03b21a2d5bc092162c8499427e659a0047'

