---
- hosts: all
  become: yes

  tasks:

  - name: Disable do firewalld
    systemd: 
      name: firewalld
      enabled: no

  - name: Stop do firewalld
    service:
      name: firewalld
      state: stopped

  - name: Disable do SELinux
    ansible.posix.selinux:
      state: disabled

